/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RequestPrintShop;

/**
 *
 * @author Lenovo
 */
public class AddBookToManageBook extends javax.swing.JFrame {

    /**
     * Creates new form AddBookToManageBook
     */
    public AddBookToManageBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        Submit = new javax.swing.JButton();
        addBookTitle = new javax.swing.JLabel();
        bookName = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        MonthSpinner = new javax.swing.JSpinner();
        yearSpinner = new javax.swing.JSpinner();
        dateSpinner = new javax.swing.JSpinner();
        detail = new javax.swing.JLabel();
        bookNameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        DetailField = new javax.swing.JTextPane();
        setPrice = new javax.swing.JLabel();
        setPriceField = new javax.swing.JTextField();
        addBy = new javax.swing.JLabel();
        addByField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        Submit.setText("Submit");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        addBookTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        addBookTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBookTitle.setText("Add book");
        getContentPane().add(addBookTitle);
        addBookTitle.setBounds(0, 10, 450, 31);

        bookName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookName.setText("Book name :");
        getContentPane().add(bookName);
        bookName.setBounds(50, 50, 90, 30);

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        date.setText("Date :");
        getContentPane().add(date);
        date.setBounds(90, 90, 50, 30);
        getContentPane().add(MonthSpinner);
        MonthSpinner.setBounds(200, 90, 100, 30);
        getContentPane().add(yearSpinner);
        yearSpinner.setBounds(300, 90, 70, 30);
        getContentPane().add(dateSpinner);
        dateSpinner.setBounds(150, 90, 50, 30);

        detail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        detail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        detail.setText("Detail :");
        getContentPane().add(detail);
        detail.setBounds(50, 130, 90, 30);

        bookNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(bookNameField);
        bookNameField.setBounds(150, 50, 220, 30);

        jScrollPane1.setViewportView(DetailField);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 130, 220, 100);

        setPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        setPrice.setText("Set price :");
        getContentPane().add(setPrice);
        setPrice.setBounds(50, 240, 90, 30);

        setPriceField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(setPriceField);
        setPriceField.setBounds(150, 240, 220, 30);

        addBy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addBy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addBy.setText("Add by :");
        getContentPane().add(addBy);
        addBy.setBounds(50, 280, 90, 30);

        addByField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(addByField);
        addByField.setBounds(150, 280, 220, 30);

        backButton.setText("Back");
        getContentPane().add(backButton);
        backButton.setBounds(130, 330, 59, 30);

        submitButton.setText("Submit");
        getContentPane().add(submitButton);
        submitButton.setBounds(240, 330, 73, 30);

        setSize(new java.awt.Dimension(466, 429));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookToManageBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookToManageBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookToManageBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookToManageBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookToManageBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane DetailField;
    private javax.swing.JSpinner MonthSpinner;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel addBookTitle;
    private javax.swing.JLabel addBy;
    private javax.swing.JTextField addByField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel bookName;
    private javax.swing.JTextField bookNameField;
    private javax.swing.JLabel date;
    private javax.swing.JSpinner dateSpinner;
    private javax.swing.JLabel detail;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel setPrice;
    private javax.swing.JTextField setPriceField;
    private javax.swing.JButton submitButton;
    private javax.swing.JSpinner yearSpinner;
    // End of variables declaration//GEN-END:variables
}
