/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RequestPrintShop;

import RequestPrintDatabase.ConnectionBuilder;
import RequestPrintLogin.LoginEPrinting;
import java.awt.*;
import java.sql.*;
import java.util.logging.*;
import javax.swing.*;

/**
 *
 * @author Lenovo
 */
public class AddBookToManageBook extends javax.swing.JFrame {

    private LoginEPrinting shopID;
    private int month;

    public int getMonth() {
        if ((monthSpinner.getValue()+"").equals("January")) {
            month = 0;
        } else if ((monthSpinner.getValue()+"").equals("February")) {
            month = 1;
        } else if ((monthSpinner.getValue()+"").equals("March")) {
            month = 2;
        } else if ((monthSpinner.getValue()+"").equals("April")) {
            month = 3;
        } else if ((monthSpinner.getValue()+"").equals("May")) {
            month = 4;
        } else if ((monthSpinner.getValue()+"").equals("June")) {
            month = 5;
        } else if ((monthSpinner.getValue()+"").equals("July")) {
            month = 6;
        } else if ((monthSpinner.getValue()+"").equals("August")) {
            month = 7;
        } else if ((monthSpinner.getValue()+"").equals("September")) {
            month = 8;
        } else if ((monthSpinner.getValue()+"").equals("October")) {
            month = 9;
        } else if ((monthSpinner.getValue()+"").equals("November")) {
            month = 10;
        } else if ((monthSpinner.getValue()+"").equals("December")) {
            month = 11;
        }
        return month;
    }

    /**
     * Creates new form AddBookToManageBook
     */
    public AddBookToManageBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        Submit = new javax.swing.JButton();
        addBookTitle = new javax.swing.JLabel();
        bookName = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        monthSpinner = new javax.swing.JSpinner();
        dateSpinner = new javax.swing.JSpinner();
        detail = new javax.swing.JLabel();
        bookNameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailField = new javax.swing.JTextPane();
        setPrice = new javax.swing.JLabel();
        setPriceField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        errorText = new javax.swing.JLabel();
        yearSpinner = new javax.swing.JSpinner();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        Submit.setText("Submit");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAutoRequestFocus(false);
        setResizable(false);
        getContentPane().setLayout(null);

        addBookTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        addBookTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBookTitle.setText("Add book");
        getContentPane().add(addBookTitle);
        addBookTitle.setBounds(0, 10, 440, 31);

        bookName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        bookName.setText("Book name :");
        getContentPane().add(bookName);
        bookName.setBounds(40, 50, 90, 30);

        date.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        date.setText("Date :");
        getContentPane().add(date);
        date.setBounds(80, 90, 50, 30);

        monthSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"}));
        getContentPane().add(monthSpinner);
        monthSpinner.setBounds(190, 90, 100, 30);

        dateSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        getContentPane().add(dateSpinner);
        dateSpinner.setBounds(140, 90, 50, 30);

        detail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        detail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        detail.setText("Detail :");
        getContentPane().add(detail);
        detail.setBounds(40, 130, 90, 30);

        bookNameField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bookNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(bookNameField);
        bookNameField.setBounds(140, 50, 220, 30);

        jScrollPane1.setViewportView(detailField);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 130, 220, 100);

        setPrice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        setPrice.setText("Set price :");
        getContentPane().add(setPrice);
        setPrice.setBounds(40, 240, 90, 30);

        setPriceField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(setPriceField);
        setPriceField.setBounds(140, 240, 220, 30);

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(submitButton);
        submitButton.setBounds(160, 300, 100, 30);

        errorText.setForeground(new java.awt.Color(255, 0, 0));
        errorText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(errorText);
        errorText.setBounds(40, 270, 360, 20);

        yearSpinner.setModel(new javax.swing.SpinnerNumberModel(1900, 1900, 2500, 1));
        yearSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(yearSpinner, "0000"));
        getContentPane().add(yearSpinner);
        yearSpinner.setBounds(290, 90, 70, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(190, 90, 90, 22);

        setSize(new java.awt.Dimension(451, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        Connection con = null;
        try {
            con = ConnectionBuilder.getConnection();
            LoginEPrinting login = new LoginEPrinting();
            PreparedStatement pstmSelect = con.prepareStatement("SELECT * FROM Product WHERE productName = ? AND ShopProfile_shopID = ?");
            pstmSelect.setString(1, bookNameField.getText());
            pstmSelect.setInt(2, login.getShopId());
            ResultSet rs = pstmSelect.executeQuery();
            if (rs.next()) {
                errorText.setText("* Note * This book already existed.");
                bookNameField.setBackground(Color.PINK);
            } else {
                PreparedStatement pstmInsert = con.prepareStatement("INSERT INTO Product (productName, date, detail, price, ShopProfile_shopID)"
                        + " VALUES (?,?,?,?,?)");
                pstmInsert.setString(1, bookNameField.getText());
                pstmInsert.setDate(2, new Date((Integer.parseInt(yearSpinner.getValue()+"")-1900), getMonth() ,Integer.parseInt(dateSpinner.getValue()+"")));
                pstmInsert.setString(3, detailField.getText());
                pstmInsert.setString(4, setPriceField.getText());
                pstmInsert.setInt(5, login.getShopId());
                pstmInsert.executeUpdate();
                System.out.println("Insert complete");
                bookNameField.setText("");
                dateSpinner.setValue(1);
                monthSpinner.setValue("January");
                yearSpinner.setValue(1900);
                detailField.setText("");
                setPriceField.setText("");
                this.setVisible(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddBookToManageBook.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void bookNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNameFieldActionPerformed
        bookNameField.setBackground(null);
    }//GEN-LAST:event_bookNameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBookToManageBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBookToManageBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBookToManageBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBookToManageBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBookToManageBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Submit;
    private javax.swing.JLabel addBookTitle;
    private javax.swing.JLabel bookName;
    private javax.swing.JTextField bookNameField;
    private javax.swing.JLabel date;
    public javax.swing.JSpinner dateSpinner;
    private javax.swing.JLabel detail;
    private javax.swing.JTextPane detailField;
    private javax.swing.JLabel errorText;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    public javax.swing.JSpinner monthSpinner;
    private javax.swing.JLabel setPrice;
    private javax.swing.JTextField setPriceField;
    private javax.swing.JButton submitButton;
    public javax.swing.JSpinner yearSpinner;
    // End of variables declaration//GEN-END:variables
}
