/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RequestPrintShop;

import RequestPrintDatabase.ConnectionBuilder;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;

/**
 *
 * @author Lenovo
 */
public class ChangeStatus extends javax.swing.JFrame {

    private String status;

    /**
     * Creates new form ChangeStatus
     */
    public ChangeStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeGroup = new javax.swing.ButtonGroup();
        changeStatusTitle = new javax.swing.JLabel();
        done = new javax.swing.JRadioButton();
        pendingResponding = new javax.swing.JRadioButton();
        waitForReceipt = new javax.swing.JRadioButton();
        pendingPayment = new javax.swing.JRadioButton();
        process = new javax.swing.JRadioButton();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        changeStatusTitle.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        changeStatusTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        changeStatusTitle.setText("Change Status");
        getContentPane().add(changeStatusTitle);
        changeStatusTitle.setBounds(0, 10, 360, 25);

        changeGroup.add(done);
        done.setText("Done");
        getContentPane().add(done);
        done.setBounds(20, 110, 81, 25);

        changeGroup.add(pendingResponding);
        pendingResponding.setText("Pending Responding");
        getContentPane().add(pendingResponding);
        pendingResponding.setBounds(20, 50, 150, 25);

        changeGroup.add(waitForReceipt);
        waitForReceipt.setText("Waiting for receipt");
        getContentPane().add(waitForReceipt);
        waitForReceipt.setBounds(200, 80, 140, 25);

        changeGroup.add(pendingPayment);
        pendingPayment.setText("Pending Payment");
        getContentPane().add(pendingPayment);
        pendingPayment.setBounds(200, 50, 140, 25);

        changeGroup.add(process);
        process.setText("Process");
        getContentPane().add(process);
        process.setBounds(20, 80, 73, 25);

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(140, 140, 80, 30);

        setSize(new java.awt.Dimension(377, 228));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        Connection con = null;
        try {
            con = ConnectionBuilder.getConnection();
            RespondPrint respond = new RespondPrint();
            PreparedStatement pstm = con.prepareStatement("UPDATE mydb.Order SET `status` = ? WHERE orderID = " + respond.getOrderId());
            if (pendingResponding.isSelected()) {
                pstm.setString(1, pendingResponding.getText());
                System.out.println("pending responding update value function working !");
            } else if (pendingPayment.isSelected()) {
                pstm.setString(1, pendingPayment.getText());
                System.out.println("pending payment update value function working !");
            } else if (process.isSelected()) {
                pstm.setString(1, process.getText());
                System.out.println("process update value function working !");
            } else if (waitForReceipt.isSelected()) {
                pstm.setString(1, "Product can be picked");
                System.out.println("wait for receipt update value function working !");
            } else if (done.isSelected()) {
                pstm.setString(1, done.getText());
                System.out.println("done update value function working !");
            }
            pstm.executeUpdate();
            System.out.println("Executed update");
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(ChangeStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Connection con = null;
        try {
            con = ConnectionBuilder.getConnection();
            System.out.println("Conbuilder");
            RespondPrint respond = new RespondPrint();
            PreparedStatement pstm = con.prepareStatement("SELECT `status` FROM mydb.Order WHERE orderID = " + respond.getOrderId());
            ResultSet rs = pstm.executeQuery();
            System.out.println(rs);
            if (rs.next()) {
                if (rs.getString("status").equals("Pending Responding")) {
                    pendingResponding.setSelected(true);
                    System.out.println("pending responding window activate function is working !");
                } else if (rs.getString("status").equals("Pending Payment")) {
                    pendingPayment.setSelected(true);
                    System.out.println("pending payment window activate function is working !");
                } else if (rs.getString("status").equals("Process")) {
                    process.setSelected(true);
                    System.out.println("process window activate function is working !");
                } else if (rs.getString("status").equals("Product can be picked")) {
                    waitForReceipt.setSelected(true);
                    System.out.println("wait for recipt window activate function is working !");
                } else if (rs.getString("status").equals("Done")) {
                    done.setSelected(true);
                    System.out.println("done window activate function is working !");
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ChangeStatus.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeStatus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeStatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup changeGroup;
    private javax.swing.JLabel changeStatusTitle;
    private javax.swing.JRadioButton done;
    private javax.swing.JRadioButton pendingPayment;
    private javax.swing.JRadioButton pendingResponding;
    private javax.swing.JRadioButton process;
    private javax.swing.JButton updateButton;
    private javax.swing.JRadioButton waitForReceipt;
    // End of variables declaration//GEN-END:variables
}
