/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RequestPrintShop;

import RequestPrintDatabase.ConnectionBuilder;
import RequestPrintLogin.StoreLogin;
import com.sun.prism.paint.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Lenovo
 */
public class ShopProfile extends javax.swing.JFrame {

    public JLabel getProfile() {
        return profile;
    }

    /**
     * Creates new form ShopProfile
     */
    public ShopProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        profileTitle = new javax.swing.JLabel();
        shopName = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        respondPrint = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        manageBook = new javax.swing.JLabel();
        bgMenu = new javax.swing.JPanel();
        profile = new javax.swing.JLabel();
        signOut = new javax.swing.JLabel();
        addressField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        shopNameField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setText("Name");
        getContentPane().add(name);
        name.setBounds(250, 70, 60, 30);

        profileTitle.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        profileTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileTitle.setText("Profile");
        getContentPane().add(profileTitle);
        profileTitle.setBounds(210, 20, 350, 40);

        shopName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        shopName.setText("Shop name");
        getContentPane().add(shopName);
        shopName.setBounds(250, 130, 80, 30);

        address.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        address.setText("Address");
        getContentPane().add(address);
        address.setBounds(250, 190, 80, 30);

        phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phone.setText("Phone");
        getContentPane().add(phone);
        phone.setBounds(250, 250, 80, 30);

        email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email.setText("E-mail");
        getContentPane().add(email);
        email.setBounds(250, 310, 80, 30);

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });
        getContentPane().add(editButton);
        editButton.setBounds(470, 380, 60, 20);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        respondPrint.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        respondPrint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        respondPrint.setText("Respond Print");
        respondPrint.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(respondPrint);
        respondPrint.setBounds(0, 250, 190, 30);

        home.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        home.setText("Home");
        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(home);
        home.setBounds(0, 100, 190, 30);

        manageBook.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        manageBook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageBook.setText("Manage Book");
        manageBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageBookMouseClicked(evt);
            }
        });
        jPanel1.add(manageBook);
        manageBook.setBounds(0, 200, 190, 30);

        bgMenu.setBackground(new java.awt.Color(204, 204, 204));
        bgMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        profile.setBackground(new java.awt.Color(153, 153, 153));
        profile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        profile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profile.setText("Profile");
        bgMenu.add(profile);

        jPanel1.add(bgMenu);
        bgMenu.setBounds(0, 150, 190, 30);

        signOut.setText("Sign out");
        signOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(signOut);
        signOut.setBounds(10, 390, 50, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 190, 420);
        getContentPane().add(addressField);
        addressField.setBounds(260, 220, 270, 30);
        getContentPane().add(nameField);
        nameField.setBounds(260, 100, 270, 30);
        getContentPane().add(shopNameField);
        shopNameField.setBounds(260, 160, 270, 30);
        getContentPane().add(phoneField);
        phoneField.setBounds(260, 280, 270, 30);
        getContentPane().add(emailField);
        emailField.setBounds(260, 340, 270, 30);

        setSize(new java.awt.Dimension(576, 462));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        EditShopProfile editSProf = new EditShopProfile();
        editSProf.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        profile.setForeground(java.awt.Color.WHITE);
        profile.setBackground(java.awt.Color.DARK_GRAY);
        bgMenu.setBackground(java.awt.Color.DARK_GRAY);
    }//GEN-LAST:event_formComponentShown

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Connection con = null;
        try {
            con = ConnectionBuilder.getConnection();
            StoreLogin sLogin = new StoreLogin();
            PreparedStatement pstm = con.prepareStatement("SELECT * FROM ShopProfile WHERE shopID = " + sLogin.getShopId());
            ResultSet rs = pstm.executeQuery();
            if (rs.next()) {
                nameField.setEditable(false);
                nameField.setText(rs.getString("ownerName") + " " + rs.getString("ownerSurname"));
                shopNameField.setEditable(false);
                shopNameField.setText(rs.getString("shopName"));
                addressField.setEditable(false);
                addressField.setText(rs.getString("address"));
                phoneField.setEditable(false);
                phoneField.setText(rs.getString("phone"));
                emailField.setEditable(false);
                emailField.setText(rs.getString("email"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ShopProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void manageBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageBookMouseClicked
        ManageListBook mlb = new ManageListBook();
        this.setVisible(false);
        mlb.setVisible(true);
    }//GEN-LAST:event_manageBookMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShopProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShopProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShopProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShopProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShopProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField addressField;
    private javax.swing.JPanel bgMenu;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel manageBook;
    private javax.swing.JLabel name;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel profile;
    private javax.swing.JLabel profileTitle;
    private javax.swing.JLabel respondPrint;
    private javax.swing.JLabel shopName;
    private javax.swing.JTextField shopNameField;
    private javax.swing.JLabel signOut;
    // End of variables declaration//GEN-END:variables
}
