/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RequestPrintUser;

import RequestPrintDatabase.ConnectionBuilder;
import RequestPrintLogin.LoginEPrinting;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jirayupeach
 */
public class EditUserProfile extends javax.swing.JFrame {

    /**
     * Creates new form EditUserProfile
     */
    public EditUserProfile() {
        initComponents();
    }
    
    public void callOldProfile() {
        try {
            Connection con = ConnectionBuilder.getConnection();
            LoginEPrinting login = new LoginEPrinting();
            PreparedStatement pstm = con.prepareStatement("SELECT * FROM UserProfile WHERE id = " + login.getUserId());
            ResultSet rs = pstm.executeQuery();
            if (rs.next()) {
                nameField.setText(rs.getString("name"));
                surnameField.setText(rs.getString("surname"));
                emailField.setText(rs.getString("email"));
                phoneField.setText(rs.getString("phone"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(EditUserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void UpdateProfile() {
        Connection con = null;
        try {
            con = ConnectionBuilder.getConnection();
            LoginEPrinting login = new LoginEPrinting();
            System.out.println(login.getUserId());
            PreparedStatement pstm = con.prepareStatement("UPDATE UserProfile SET name=?, surname=?, email=?, phone=? WHERE id = "+ login.getUserId());
            pstm.setString(1, nameField.getText());
            pstm.setString(2, surnameField.getText());
            pstm.setString(3, emailField.getText());
            pstm.setInt(4, Integer.parseInt(phoneField.getText()));
            
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(null, "Save Successful");
            
            this.setVisible(false);
            con.close();
            pstm.close();
        } catch (SQLException ex) {
            Logger.getLogger(EditUserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        surnameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        SaveBox = new javax.swing.JPanel();
        Save = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(470, 300));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Moon", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Profile");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 10, 470, 40);

        jLabel2.setFont(new java.awt.Font("Moon", 1, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Name : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 60, 90, 30);

        jLabel3.setFont(new java.awt.Font("Moon", 1, 16)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Surname : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 110, 30);

        jLabel4.setFont(new java.awt.Font("Moon", 1, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Email : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 140, 90, 30);

        phone.setFont(new java.awt.Font("Moon", 1, 16)); // NOI18N
        phone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        phone.setText("Telephone : ");
        getContentPane().add(phone);
        phone.setBounds(20, 180, 120, 30);
        getContentPane().add(nameField);
        nameField.setBounds(140, 60, 300, 30);
        getContentPane().add(surnameField);
        surnameField.setBounds(140, 100, 300, 30);
        getContentPane().add(emailField);
        emailField.setBounds(140, 140, 300, 30);
        getContentPane().add(phoneField);
        phoneField.setBounds(140, 180, 300, 30);

        SaveBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveBoxMouseClicked(evt);
            }
        });
        SaveBox.setLayout(null);

        Save.setFont(new java.awt.Font("Cloud Light", 0, 18)); // NOI18N
        Save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Save.setText("Save");
        Save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveBox.add(Save);
        Save.setBounds(0, 0, 410, 40);

        getContentPane().add(SaveBox);
        SaveBox.setBounds(30, 230, 410, 40);

        setSize(new java.awt.Dimension(473, 325));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        getContentPane().setBackground(new java.awt.Color(228,228,228));
        SaveBox.setBackground(new java.awt.Color(153,255,153));
        Save.setForeground(Color.black);
        callOldProfile();
    }//GEN-LAST:event_formComponentShown

    private void SaveBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBoxMouseClicked
        // TODO add your handling code here:
         Connection con = null;
        try {
            con = ConnectionBuilder.getConnection();
            LoginEPrinting login = new LoginEPrinting();
            System.out.println(login.getUserId());
            PreparedStatement pstm = con.prepareStatement("UPDATE UserProfile SET name=?, surname=?, email=?, phone=? WHERE id = "+ login.getUserId());
            pstm.setString(1, nameField.getText());
            pstm.setString(2, surnameField.getText());
            pstm.setString(3, emailField.getText());
            pstm.setInt(4, Integer.parseInt(phoneField.getText()));
            
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(null, "Save Successful");
            
            this.setVisible(false);
            con.close();
            pstm.close();
        } catch (SQLException ex) {
            Logger.getLogger(EditUserProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_SaveBoxMouseClicked
   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditUserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditUserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditUserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditUserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditUserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Save;
    private javax.swing.JPanel SaveBox;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel phone;
    private javax.swing.JTextField phoneField;
    private javax.swing.JTextField surnameField;
    // End of variables declaration//GEN-END:variables
}
