/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RequestPrintUser;

import RequestPrintDatabase.ConnectionBuilder;
import RequestPrintLogin.LoginEPrinting;
import RequestPrintShop.EditShopProfile;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Userprofile extends javax.swing.JFrame {
    
    private String Username;
    private int UserId;

    public Userprofile() {
        initComponents();
    }

    public void setUsername(String Username) {
        this.Username = Username;
    }

    public void setUserId(int UserId) {
        this.UserId = UserId;
    }
    
    public void EditProfile() {
        EditUserProfile editUProf = new EditUserProfile();
        editUProf.setVisible(true);
    }
    
    public void fetchProfile() {
        try {
            // TODO add your handling code here:
            Connection con = null;
            con = ConnectionBuilder.getConnection();
            LoginEPrinting login = new LoginEPrinting();
            PreparedStatement pstm = con.prepareStatement("SELECT name,surname,email,phone FROM UserProfile WHERE id = " + login.getUserId());
            ResultSet rs = pstm.executeQuery();
            System.out.println(login.getUserId());
            while(rs.next()) {
                NameLabel.setText(rs.getString("name"));
                NameLabel.setEditable(false);
                SurnameLabel.setText(rs.getString("surname"));
                SurnameLabel.setEditable(false);
                EmailLabel.setText(rs.getString("email"));
                EmailLabel.setEditable(false);
                PhoneLabel.setText(rs.getString("phone"));
                PhoneLabel.setEditable(false);
            }
            con.close();
            pstm.close();
        } catch (SQLException ex) {
            Logger.getLogger(Userprofile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void callBookList() {
        BookList book = new BookList();
        book.setUserId(UserId);
        book.setUsername(Username);
        book.setVisible(true);
        setVisible(false);
    }
    
    public void Logout() {
        System.exit(0);
    }
    
    public void callHome() {
        Home h = new Home();
        h.setUserId(UserId);
        h.setUsername(Username);
        h.setVisible(true);
        setVisible(false);
    }
    
    public void callRequestPage() {
        UserRequest userreq = new UserRequest();
        userreq.setUserId(UserId);
        userreq.setUsername(Username);
        userreq.setVisible(true);
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Surname = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        Navbar = new javax.swing.JPanel();
        HomeBox = new javax.swing.JPanel();
        HomeLabel = new javax.swing.JLabel();
        YourProfileBox = new javax.swing.JPanel();
        YourProfileLabel = new javax.swing.JLabel();
        RequestBox = new javax.swing.JPanel();
        RequestLabel = new javax.swing.JLabel();
        BookListBox = new javax.swing.JPanel();
        BookListLabel = new javax.swing.JLabel();
        LogoutBox = new javax.swing.JPanel();
        LogoutLabel = new javax.swing.JLabel();
        EditBox = new javax.swing.JPanel();
        Edit = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JTextField();
        PhoneLabel = new javax.swing.JTextField();
        SurnameLabel = new javax.swing.JTextField();
        NameLabel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Moon", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Your Profile");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 20, 390, 40);

        Name.setFont(new java.awt.Font("Moon", 1, 16)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Name.setText("Name : ");
        getContentPane().add(Name);
        Name.setBounds(220, 100, 130, 30);

        Surname.setFont(new java.awt.Font("Moon", 1, 16)); // NOI18N
        Surname.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Surname.setText("Surname : ");
        getContentPane().add(Surname);
        Surname.setBounds(220, 140, 130, 30);

        Email.setFont(new java.awt.Font("Moon", 1, 16)); // NOI18N
        Email.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Email.setText("Email : ");
        getContentPane().add(Email);
        Email.setBounds(220, 180, 130, 30);

        Phone.setFont(new java.awt.Font("Moon", 1, 16)); // NOI18N
        Phone.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Phone.setText("Telephone : ");
        getContentPane().add(Phone);
        Phone.setBounds(220, 220, 130, 30);

        Navbar.setLayout(null);

        HomeBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HomeBox.setPreferredSize(new java.awt.Dimension(210, 51));
        HomeBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeBoxMouseExited(evt);
            }
        });
        HomeBox.setLayout(null);

        HomeLabel.setFont(new java.awt.Font("Cloud Light", 1, 18)); // NOI18N
        HomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLabel.setText("Home");
        HomeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBox.add(HomeLabel);
        HomeLabel.setBounds(0, 0, 220, 40);

        Navbar.add(HomeBox);
        HomeBox.setBounds(0, 100, 220, 40);

        YourProfileBox.setPreferredSize(new java.awt.Dimension(210, 51));
        YourProfileBox.setLayout(null);

        YourProfileLabel.setFont(new java.awt.Font("Cloud Light", 1, 18)); // NOI18N
        YourProfileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YourProfileLabel.setText("Your Profile");
        YourProfileLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        YourProfileBox.add(YourProfileLabel);
        YourProfileLabel.setBounds(0, 0, 220, 40);

        Navbar.add(YourProfileBox);
        YourProfileBox.setBounds(0, 150, 220, 40);

        RequestBox.setPreferredSize(new java.awt.Dimension(210, 51));
        RequestBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RequestBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RequestBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RequestBoxMouseExited(evt);
            }
        });
        RequestBox.setLayout(null);

        RequestLabel.setFont(new java.awt.Font("Cloud Light", 1, 18)); // NOI18N
        RequestLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RequestLabel.setText("Request to Print");
        RequestLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RequestBox.add(RequestLabel);
        RequestLabel.setBounds(0, 0, 220, 40);

        Navbar.add(RequestBox);
        RequestBox.setBounds(0, 200, 220, 40);

        BookListBox.setPreferredSize(new java.awt.Dimension(210, 51));
        BookListBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookListBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BookListBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BookListBoxMouseExited(evt);
            }
        });
        BookListBox.setLayout(null);

        BookListLabel.setFont(new java.awt.Font("Cloud Light", 1, 18)); // NOI18N
        BookListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookListLabel.setText("Book List");
        BookListLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BookListBox.add(BookListLabel);
        BookListLabel.setBounds(0, 0, 220, 40);

        Navbar.add(BookListBox);
        BookListBox.setBounds(0, 250, 220, 40);

        LogoutBox.setPreferredSize(new java.awt.Dimension(210, 51));
        LogoutBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutBoxMouseExited(evt);
            }
        });
        LogoutBox.setLayout(null);

        LogoutLabel.setFont(new java.awt.Font("Cloud Light", 1, 18)); // NOI18N
        LogoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoutLabel.setText("Logout");
        LogoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LogoutBox.add(LogoutLabel);
        LogoutLabel.setBounds(0, 0, 220, 40);

        Navbar.add(LogoutBox);
        LogoutBox.setBounds(0, 300, 220, 40);

        getContentPane().add(Navbar);
        Navbar.setBounds(0, 0, 220, 550);

        EditBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBoxMouseClicked(evt);
            }
        });
        EditBox.setLayout(null);

        Edit.setFont(new java.awt.Font("Cloud Light", 0, 18)); // NOI18N
        Edit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Edit.setText("Edit");
        Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditBox.add(Edit);
        Edit.setBounds(0, 0, 340, 40);

        getContentPane().add(EditBox);
        EditBox.setBounds(240, 300, 340, 40);

        EmailLabel.setFont(new java.awt.Font("Cloud Light", 0, 16)); // NOI18N
        getContentPane().add(EmailLabel);
        EmailLabel.setBounds(360, 180, 210, 30);

        PhoneLabel.setFont(new java.awt.Font("Cloud Light", 0, 16)); // NOI18N
        getContentPane().add(PhoneLabel);
        PhoneLabel.setBounds(360, 220, 210, 30);

        SurnameLabel.setFont(new java.awt.Font("Cloud Light", 0, 16)); // NOI18N
        getContentPane().add(SurnameLabel);
        SurnameLabel.setBounds(360, 140, 210, 30);

        NameLabel.setFont(new java.awt.Font("Cloud Light", 0, 16)); // NOI18N
        getContentPane().add(NameLabel);
        NameLabel.setBounds(360, 100, 210, 30);

        setSize(new java.awt.Dimension(616, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Edit.setForeground(Color.black);
        EditBox.setBackground(new java.awt.Color(153,255,153));
        YourProfileLabel.setForeground(Color.black);
        YourProfileBox.setBackground(new java.awt.Color(228,228,228));
        RequestBox.setBackground(new java.awt.Color(102,102,102));
        LogoutBox.setBackground(new java.awt.Color(102,102,102));
        BookListBox.setBackground(new java.awt.Color(102,102,102));
        HomeBox.setBackground(new java.awt.Color(102,102,102));
        Navbar.setBackground(new java.awt.Color(102,102,102));
        getContentPane().setBackground(new java.awt.Color(228,228,228));
        HomeLabel.setForeground(Color.white);
        BookListLabel.setForeground(Color.white);
        RequestLabel.setForeground(Color.white);
        LogoutLabel.setForeground(Color.white);
        fetchProfile();
    }//GEN-LAST:event_formWindowActivated

    private void HomeBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBoxMouseEntered
        // TODO add your handling code here:
        HomeBox.setBackground(new java.awt.Color(228,228,228));
        HomeLabel.setForeground(Color.black);
    }//GEN-LAST:event_HomeBoxMouseEntered

    private void HomeBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBoxMouseExited
        // TODO add your handling code here:
        HomeBox.setBackground(null);
        HomeLabel.setForeground(Color.white);
    }//GEN-LAST:event_HomeBoxMouseExited

    private void RequestBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RequestBoxMouseEntered
        // TODO add your handling code here:
        RequestBox.setBackground(new java.awt.Color(228,228,228));
        RequestLabel.setForeground(Color.black);
    }//GEN-LAST:event_RequestBoxMouseEntered

    private void RequestBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RequestBoxMouseExited
        // TODO add your handling code here:
        RequestBox.setBackground(null);
        RequestLabel.setForeground(Color.white);
    }//GEN-LAST:event_RequestBoxMouseExited

    private void BookListBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookListBoxMouseEntered
        // TODO add your handling code here:
        BookListLabel.setForeground(Color.black);
        BookListBox.setBackground(new java.awt.Color(228,228,228));
    }//GEN-LAST:event_BookListBoxMouseEntered

    private void BookListBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookListBoxMouseExited
        // TODO add your handling code here:
        BookListLabel.setForeground(Color.white);
        BookListBox.setBackground(null);
    }//GEN-LAST:event_BookListBoxMouseExited

    private void LogoutBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBoxMouseEntered
        // TODO add your handling code here:
        LogoutBox.setBackground(new java.awt.Color(228,228,228));
        LogoutLabel.setForeground(Color.black);
    }//GEN-LAST:event_LogoutBoxMouseEntered

    private void LogoutBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBoxMouseExited
        // TODO add your handling code here:
        LogoutBox.setBackground(null);
        LogoutLabel.setForeground(Color.white);
    }//GEN-LAST:event_LogoutBoxMouseExited

    private void LogoutBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBoxMouseClicked
        // TODO add your handling code here:
        Logout();
    }//GEN-LAST:event_LogoutBoxMouseClicked

    private void BookListBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookListBoxMouseClicked
        // TODO add your handling code here:
        callBookList();
    }//GEN-LAST:event_BookListBoxMouseClicked

    private void HomeBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBoxMouseClicked
        // TODO add your handling code here:
        callHome();
    }//GEN-LAST:event_HomeBoxMouseClicked

    private void RequestBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RequestBoxMouseClicked
        // TODO add your handling code here:
        callRequestPage();
    }//GEN-LAST:event_RequestBoxMouseClicked

    private void EditBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBoxMouseClicked
       EditProfile();
    }//GEN-LAST:event_EditBoxMouseClicked

    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookListBox;
    private javax.swing.JLabel BookListLabel;
    private javax.swing.JLabel Edit;
    private javax.swing.JPanel EditBox;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailLabel;
    private javax.swing.JPanel HomeBox;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JPanel LogoutBox;
    private javax.swing.JLabel LogoutLabel;
    private javax.swing.JLabel Name;
    private javax.swing.JTextField NameLabel;
    private javax.swing.JPanel Navbar;
    private javax.swing.JLabel Phone;
    private javax.swing.JTextField PhoneLabel;
    private javax.swing.JPanel RequestBox;
    private javax.swing.JLabel RequestLabel;
    private javax.swing.JLabel Surname;
    private javax.swing.JTextField SurnameLabel;
    private javax.swing.JPanel YourProfileBox;
    private javax.swing.JLabel YourProfileLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
