/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RequestPrintUser;

import RequestPrintDatabase.ConnectionBuilder;
import RequestPrintLogin.LoginEPrinting;
import RequestPrintShop.EditShopProfile;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Userprofile extends javax.swing.JFrame {
    
    private String Username;
    private int UserId;

    public Userprofile() {
        initComponents();
    }

    public void setUsername(String Username) {
        this.Username = Username;
    }

    public void setUserId(int UserId) {
        this.UserId = UserId;
    }
    
    public void EditProfile() {
        EditUserProfile editUProf = new EditUserProfile();
        editUProf.setVisible(true);
    }
    
    public void fetchProfile() {
        try {
            // TODO add your handling code here:
            Connection con = null;
            con = ConnectionBuilder.getConnection();
            LoginEPrinting login = new LoginEPrinting();
            PreparedStatement pstm = con.prepareStatement("SELECT name,surname,email,phone FROM UserProfile WHERE id = " + login.getUserId());
            ResultSet rs = pstm.executeQuery();
            System.out.println(login.getUserId());
            while(rs.next()) {
                System.out.println("a");
                NameLabel.setText(rs.getString("name"));
                SurnameLabel.setText(rs.getString("surname"));
                EmailLabel.setText(rs.getString("email"));
                PhoneLabel.setText(rs.getString("phone"));
            }
            con.close();
            pstm.close();
        } catch (SQLException ex) {
            Logger.getLogger(Userprofile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void callBookList() {
        BookList book = new BookList();
        book.setUserId(UserId);
        book.setUsername(Username);
        book.setVisible(true);
        setVisible(false);
    }
    
    public void Logout() {
        System.exit(0);
    }
    
    public void callHome() {
        Home h = new Home();
        h.setUserId(UserId);
        h.setUsername(Username);
        h.setVisible(true);
        setVisible(false);
    }
    
    public void callRequestPage() {
        UserRequest userreq = new UserRequest();
        userreq.setUserId(UserId);
        userreq.setUsername(Username);
        userreq.setVisible(true);
        setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Surname = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        SurnameLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        Navbar = new javax.swing.JPanel();
        HomeBox = new javax.swing.JPanel();
        HomeLabel = new javax.swing.JLabel();
        YourProfileBox = new javax.swing.JPanel();
        YourProfileLabel = new javax.swing.JLabel();
        RequestBox = new javax.swing.JPanel();
        RequestLabel = new javax.swing.JLabel();
        BookListBox = new javax.swing.JPanel();
        BookListLabel = new javax.swing.JLabel();
        LogoutBox = new javax.swing.JPanel();
        LogoutLabel = new javax.swing.JLabel();
        EditBox = new javax.swing.JPanel();
        Edit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nithan", 0, 28)); // NOI18N
        jLabel1.setText("Your Profile");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(419, 30, 143, 37);

        Name.setFont(new java.awt.Font("supermarket", 0, 14)); // NOI18N
        Name.setText("Name : ");
        getContentPane().add(Name);
        Name.setBounds(282, 104, 41, 55);

        Surname.setFont(new java.awt.Font("supermarket", 0, 14)); // NOI18N
        Surname.setText("Surname : ");
        getContentPane().add(Surname);
        Surname.setBounds(266, 172, 57, 38);

        Email.setFont(new java.awt.Font("supermarket", 0, 14)); // NOI18N
        Email.setText("Email : ");
        getContentPane().add(Email);
        Email.setBounds(284, 217, 39, 62);

        Phone.setFont(new java.awt.Font("supermarket", 0, 14)); // NOI18N
        Phone.setText("Telephone : ");
        getContentPane().add(Phone);
        Phone.setBounds(266, 288, 66, 36);

        NameLabel.setFont(new java.awt.Font("supermarket", 0, 14)); // NOI18N
        getContentPane().add(NameLabel);
        NameLabel.setBounds(341, 127, 307, 17);

        SurnameLabel.setFont(new java.awt.Font("supermarket", 0, 14)); // NOI18N
        getContentPane().add(SurnameLabel);
        SurnameLabel.setBounds(341, 181, 307, 18);

        EmailLabel.setFont(new java.awt.Font("supermarket", 0, 14)); // NOI18N
        getContentPane().add(EmailLabel);
        EmailLabel.setBounds(341, 240, 307, 18);

        PhoneLabel.setFont(new java.awt.Font("supermarket", 0, 14)); // NOI18N
        getContentPane().add(PhoneLabel);
        PhoneLabel.setBounds(358, 288, 307, 36);

        Navbar.setLayout(null);

        HomeBox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HomeBox.setPreferredSize(new java.awt.Dimension(210, 51));
        HomeBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                HomeBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                HomeBoxMouseExited(evt);
            }
        });
        HomeBox.setLayout(null);

        HomeLabel.setFont(new java.awt.Font("Cloud Light", 1, 18)); // NOI18N
        HomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLabel.setText("Home");
        HomeBox.add(HomeLabel);
        HomeLabel.setBounds(0, 0, 220, 40);

<<<<<<< HEAD
        Navbar.add(HomeBox);
        HomeBox.setBounds(0, 80, 220, 40);
=======
        javax.swing.GroupLayout HomeBoxLayout = new javax.swing.GroupLayout(HomeBox);
        HomeBox.setLayout(HomeBoxLayout);
        HomeBoxLayout.setHorizontalGroup(
            HomeBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeBoxLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(HomeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        HomeBoxLayout.setVerticalGroup(
            HomeBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeLabel)
                .addContainerGap())
        );
>>>>>>> 46ac26fc301b8b985724c436ebb3fef8dce39ff1

        YourProfileBox.setPreferredSize(new java.awt.Dimension(210, 51));
        YourProfileBox.setLayout(null);

        YourProfileLabel.setFont(new java.awt.Font("Cloud Light", 1, 18)); // NOI18N
        YourProfileLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        YourProfileLabel.setText("Your Profile");
        YourProfileBox.add(YourProfileLabel);
        YourProfileLabel.setBounds(0, 0, 220, 40);

<<<<<<< HEAD
        Navbar.add(YourProfileBox);
        YourProfileBox.setBounds(0, 140, 220, 40);
=======
        javax.swing.GroupLayout YourProfileBoxLayout = new javax.swing.GroupLayout(YourProfileBox);
        YourProfileBox.setLayout(YourProfileBoxLayout);
        YourProfileBoxLayout.setHorizontalGroup(
            YourProfileBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(YourProfileBoxLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(YourProfileLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        YourProfileBoxLayout.setVerticalGroup(
            YourProfileBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, YourProfileBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(YourProfileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
>>>>>>> 46ac26fc301b8b985724c436ebb3fef8dce39ff1

        RequestBox.setPreferredSize(new java.awt.Dimension(210, 51));
        RequestBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RequestBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RequestBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RequestBoxMouseExited(evt);
            }
        });
        RequestBox.setLayout(null);

        RequestLabel.setFont(new java.awt.Font("Cloud Light", 1, 18)); // NOI18N
        RequestLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RequestLabel.setText("Request to Print");
        RequestBox.add(RequestLabel);
        RequestLabel.setBounds(0, 0, 220, 40);

<<<<<<< HEAD
        Navbar.add(RequestBox);
        RequestBox.setBounds(0, 200, 220, 40);
=======
        javax.swing.GroupLayout RequestBoxLayout = new javax.swing.GroupLayout(RequestBox);
        RequestBox.setLayout(RequestBoxLayout);
        RequestBoxLayout.setHorizontalGroup(
            RequestBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RequestBoxLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(RequestLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RequestBoxLayout.setVerticalGroup(
            RequestBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RequestBoxLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RequestLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
>>>>>>> 46ac26fc301b8b985724c436ebb3fef8dce39ff1

        BookListBox.setPreferredSize(new java.awt.Dimension(210, 51));
        BookListBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BookListBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BookListBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BookListBoxMouseExited(evt);
            }
        });
        BookListBox.setLayout(null);

        BookListLabel.setFont(new java.awt.Font("Cloud Light", 1, 18)); // NOI18N
        BookListLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BookListLabel.setText("Book List");
        BookListBox.add(BookListLabel);
        BookListLabel.setBounds(0, 0, 220, 40);

<<<<<<< HEAD
        Navbar.add(BookListBox);
        BookListBox.setBounds(0, 260, 220, 40);
=======
        javax.swing.GroupLayout BookListBoxLayout = new javax.swing.GroupLayout(BookListBox);
        BookListBox.setLayout(BookListBoxLayout);
        BookListBoxLayout.setHorizontalGroup(
            BookListBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BookListBoxLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(BookListLabel)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        BookListBoxLayout.setVerticalGroup(
            BookListBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BookListBoxLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BookListLabel)
                .addContainerGap())
        );
>>>>>>> 46ac26fc301b8b985724c436ebb3fef8dce39ff1

        LogoutBox.setPreferredSize(new java.awt.Dimension(210, 51));
        LogoutBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBoxMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LogoutBoxMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LogoutBoxMouseExited(evt);
            }
        });
        LogoutBox.setLayout(null);

        LogoutLabel.setFont(new java.awt.Font("Cloud Light", 1, 18)); // NOI18N
        LogoutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoutLabel.setText("Logout");
        LogoutBox.add(LogoutLabel);
        LogoutLabel.setBounds(0, 0, 220, 40);

        Navbar.add(LogoutBox);
        LogoutBox.setBounds(0, 320, 220, 40);

<<<<<<< HEAD
        getContentPane().add(Navbar);
        Navbar.setBounds(0, 0, 220, 500);
=======
        javax.swing.GroupLayout NavbarLayout = new javax.swing.GroupLayout(Navbar);
        Navbar.setLayout(NavbarLayout);
        NavbarLayout.setHorizontalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
            .addComponent(RequestBox, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addGroup(NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LogoutBox, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addGroup(NavbarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BookListBox, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(YourProfileBox, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addContainerGap())
        );
        NavbarLayout.setVerticalGroup(
            NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(YourProfileBox, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RequestBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BookListBox, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LogoutBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );
>>>>>>> 46ac26fc301b8b985724c436ebb3fef8dce39ff1

        EditBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditBoxMouseClicked(evt);
            }
        });

        Edit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        Edit.setText("Edit");

        javax.swing.GroupLayout EditBoxLayout = new javax.swing.GroupLayout(EditBox);
        EditBox.setLayout(EditBoxLayout);
        EditBoxLayout.setHorizontalGroup(
            EditBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditBoxLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Edit)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        EditBoxLayout.setVerticalGroup(
            EditBoxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditBoxLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Edit)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(EditBox);
        EditBox.setBounds(523, 342, 105, 55);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Edit.setForeground(Color.black);
        EditBox.setBackground(new java.awt.Color(153,255,153));
        YourProfileLabel.setForeground(Color.black);
        YourProfileBox.setBackground(new java.awt.Color(228,228,228));
        RequestBox.setBackground(new java.awt.Color(102,102,102));
        LogoutBox.setBackground(new java.awt.Color(102,102,102));
        BookListBox.setBackground(new java.awt.Color(102,102,102));
        HomeBox.setBackground(new java.awt.Color(102,102,102));
        Navbar.setBackground(new java.awt.Color(102,102,102));
        getContentPane().setBackground(new java.awt.Color(228,228,228));
        HomeLabel.setForeground(Color.white);
        BookListLabel.setForeground(Color.white);
        RequestLabel.setForeground(Color.white);
        LogoutLabel.setForeground(Color.white);
        fetchProfile();
    }//GEN-LAST:event_formWindowActivated

    private void HomeBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBoxMouseEntered
        // TODO add your handling code here:
        HomeBox.setBackground(new java.awt.Color(228,228,228));
        HomeLabel.setForeground(Color.black);
    }//GEN-LAST:event_HomeBoxMouseEntered

    private void HomeBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBoxMouseExited
        // TODO add your handling code here:
        HomeBox.setBackground(null);
        HomeLabel.setForeground(Color.white);
    }//GEN-LAST:event_HomeBoxMouseExited

    private void RequestBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RequestBoxMouseEntered
        // TODO add your handling code here:
        RequestBox.setBackground(new java.awt.Color(228,228,228));
        RequestLabel.setForeground(Color.black);
    }//GEN-LAST:event_RequestBoxMouseEntered

    private void RequestBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RequestBoxMouseExited
        // TODO add your handling code here:
        RequestBox.setBackground(null);
        RequestLabel.setForeground(Color.white);
    }//GEN-LAST:event_RequestBoxMouseExited

    private void BookListBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookListBoxMouseEntered
        // TODO add your handling code here:
        BookListLabel.setForeground(Color.black);
        BookListBox.setBackground(new java.awt.Color(228,228,228));
    }//GEN-LAST:event_BookListBoxMouseEntered

    private void BookListBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookListBoxMouseExited
        // TODO add your handling code here:
        BookListLabel.setForeground(Color.white);
        BookListBox.setBackground(null);
    }//GEN-LAST:event_BookListBoxMouseExited

    private void LogoutBoxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBoxMouseEntered
        // TODO add your handling code here:
        LogoutBox.setBackground(new java.awt.Color(228,228,228));
        LogoutLabel.setForeground(Color.black);
    }//GEN-LAST:event_LogoutBoxMouseEntered

    private void LogoutBoxMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBoxMouseExited
        // TODO add your handling code here:
        LogoutBox.setBackground(null);
        LogoutLabel.setForeground(Color.white);
    }//GEN-LAST:event_LogoutBoxMouseExited

    private void LogoutBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBoxMouseClicked
        // TODO add your handling code here:
        Logout();
    }//GEN-LAST:event_LogoutBoxMouseClicked

    private void BookListBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BookListBoxMouseClicked
        // TODO add your handling code here:
        callBookList();
    }//GEN-LAST:event_BookListBoxMouseClicked

    private void HomeBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeBoxMouseClicked
        // TODO add your handling code here:
        callHome();
    }//GEN-LAST:event_HomeBoxMouseClicked

    private void RequestBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RequestBoxMouseClicked
        // TODO add your handling code here:
        callRequestPage();
    }//GEN-LAST:event_RequestBoxMouseClicked

    private void EditBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditBoxMouseClicked
       EditProfile();
    }//GEN-LAST:event_EditBoxMouseClicked

    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Userprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Userprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BookListBox;
    private javax.swing.JLabel BookListLabel;
    private javax.swing.JLabel Edit;
    private javax.swing.JPanel EditBox;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JPanel HomeBox;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JPanel LogoutBox;
    private javax.swing.JLabel LogoutLabel;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JPanel Navbar;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel PhoneLabel;
    private javax.swing.JPanel RequestBox;
    private javax.swing.JLabel RequestLabel;
    private javax.swing.JLabel Surname;
    private javax.swing.JLabel SurnameLabel;
    private javax.swing.JPanel YourProfileBox;
    private javax.swing.JLabel YourProfileLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
