/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RequestPrintLogin;

import RequestPrintDatabase.ConnectionBuilder;
import RequestPrintShop.ShopProfile;
import RequestPrintUser.Userprofile;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class LoginEPrinting extends javax.swing.JFrame {

    private static int shopId;
    private static int userId;

    public static int getUserId() {
        return userId;
    }

    public int getShopId() {
        return shopId;
    }

    /**
     * Creates new form LoginEPrinting
     */
    public LoginEPrinting() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        concept = new javax.swing.JLabel();
        ePrinting = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        password = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        userName = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        signinBG = new javax.swing.JPanel();
        signin = new javax.swing.JLabel();
        errorText = new javax.swing.JLabel();
        line = new javax.swing.JLabel();
        registerBG = new javax.swing.JPanel();
        register = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        leftPanel.setBackground(new java.awt.Color(51, 51, 51));
        leftPanel.setLayout(null);

        concept.setFont(new java.awt.Font("Cloud Light", 0, 14)); // NOI18N
        concept.setForeground(new java.awt.Color(255, 255, 255));
        concept.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        concept.setText("Easy Print with E - Printing");
        leftPanel.add(concept);
        concept.setBounds(140, 295, 230, 20);

        ePrinting.setFont(new java.awt.Font("Moon", 1, 36)); // NOI18N
        ePrinting.setForeground(new java.awt.Color(255, 255, 255));
        ePrinting.setText("E - Printing");
        leftPanel.add(ePrinting);
        ePrinting.setBounds(140, 240, 240, 80);

        getContentPane().add(leftPanel);
        leftPanel.setBounds(0, 0, 390, 590);

        rightPanel.setBackground(new java.awt.Color(204, 204, 204));
        rightPanel.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Moon", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sign in to E - Printing");
        rightPanel.add(jLabel3);
        jLabel3.setBounds(0, 117, 460, 22);

        jPanel1.setLayout(null);

        password.setFont(new java.awt.Font("Moon", 1, 13)); // NOI18N
        password.setText("Password :");
        jPanel1.add(password);
        password.setBounds(10, 100, 80, 16);
        jPanel1.add(userNameField);
        userNameField.setBounds(20, 40, 340, 40);

        userName.setFont(new java.awt.Font("Moon", 1, 13)); // NOI18N
        userName.setText("Username :");
        jPanel1.add(userName);
        userName.setBounds(10, 20, 80, 16);
        jPanel1.add(passwordField);
        passwordField.setBounds(20, 120, 340, 40);

        signinBG.setBackground(new java.awt.Color(153, 255, 153));
        signinBG.setLayout(null);

        signin.setFont(new java.awt.Font("Cloud Light", 0, 24)); // NOI18N
        signin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signin.setText("Sign in");
        signin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signinMouseClicked(evt);
            }
        });
        signinBG.add(signin);
        signin.setBounds(0, 0, 340, 40);

        jPanel1.add(signinBG);
        signinBG.setBounds(20, 200, 340, 40);

        errorText.setFont(new java.awt.Font("Cloud Light", 0, 13)); // NOI18N
        errorText.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.add(errorText);
        errorText.setBounds(20, 160, 340, 40);

        rightPanel.add(jPanel1);
        jPanel1.setBounds(40, 160, 380, 250);

        line.setForeground(new java.awt.Color(102, 102, 102));
        line.setText("----------------------------------   or    ----------------------------------");
        rightPanel.add(line);
        line.setBounds(40, 420, 380, 16);

        registerBG.setBackground(new java.awt.Color(204, 255, 255));
        registerBG.setLayout(null);

        register.setFont(new java.awt.Font("Cloud Light", 0, 24)); // NOI18N
        register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register.setText("Register");
        register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        registerBG.add(register);
        register.setBounds(0, 0, 380, 40);

        rightPanel.add(registerBG);
        registerBG.setBounds(40, 450, 380, 40);

        getContentPane().add(rightPanel);
        rightPanel.setBounds(390, 0, 470, 590);

        setSize(new java.awt.Dimension(868, 622));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signinMouseClicked
        Connection con = null;
        if (userNameField.getText().equals("") && passwordField.getText().equals("")) {
            errorText.setText("Please enter your username and password!");
        } else {
            try {
                con = ConnectionBuilder.getConnection();
                //Prepared Statement Shop
                PreparedStatement pstmShop = con.prepareStatement("SELECT * FROM ShopProfile WHERE username = ? AND password = ?");
                pstmShop.setString(1, userNameField.getText());
                pstmShop.setString(2, passwordField.getText());
                ResultSet rsShop = pstmShop.executeQuery();
                //Prepared Statement User
                PreparedStatement pstmUser = con.prepareStatement("SELECT * FROM UserProfile WHERE username = ? and password = ?");
                pstmUser.setString(1, userNameField.getText());
                pstmUser.setString(2, passwordField.getText());
                ResultSet rsUser = pstmUser.executeQuery();
                
                if (rsShop.next()) {
                    shopId = Integer.parseInt(rsShop.getString("shopID"));
                    JOptionPane.showMessageDialog(null, "Success");
                    ShopProfile sProf = new ShopProfile();
                    this.setVisible(false);
                    sProf.setVisible(true);
                } else if (rsUser.next()) {
                    userId = Integer.parseInt(rsUser.getString("ID"));
                    JOptionPane.showMessageDialog(null, "Success");
                    Userprofile uProf = new Userprofile();
                    this.setVisible(false);
                    uProf.setVisible(true);
                } else {
                    userNameField.setText("");
                    passwordField.setText("");
                    errorText.setText("Invalid username or password");
                }
            } catch (SQLException ex) {
                Logger.getLogger(LoginEPrinting.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_signinMouseClicked

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        SelectRegisUserOrRegisShop selectRegis = new SelectRegisUserOrRegisShop();
        selectRegis.setVisible(true);
        selectRegis.linkToLoginEPrinting(this);
    }//GEN-LAST:event_registerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginEPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginEPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginEPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginEPrinting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginEPrinting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel concept;
    private javax.swing.JLabel ePrinting;
    private javax.swing.JLabel errorText;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel line;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel register;
    private javax.swing.JPanel registerBG;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel signin;
    private javax.swing.JPanel signinBG;
    private javax.swing.JLabel userName;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables
}
