/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RequestPrintLogin;

import RequestPrintShop.RegisterShop;
import RequestPrintUser.RegisterUser;

/**
 *
 * @author Lenovo
 */
public class SelectRegisUserOrRegisShop extends javax.swing.JFrame {

    public LoginEPrinting controlLoginEPrinting;

    public void linkToLoginEPrinting(LoginEPrinting control) {
        controlLoginEPrinting = control;
    }

    /**
     * Creates new form SelectRegisUserOrRegisShop
     */
    public SelectRegisUserOrRegisShop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        questionSelectRegis = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        regisShopBG = new javax.swing.JPanel();
        shopRegisLabelButton = new javax.swing.JLabel();
        regisUserBG = new javax.swing.JPanel();
        userRegisLabelButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        questionSelectRegis.setFont(new java.awt.Font("Moon", 1, 24)); // NOI18N
        questionSelectRegis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionSelectRegis.setText("Who are you ?");
        getContentPane().add(questionSelectRegis);
        questionSelectRegis.setBounds(0, 20, 450, 41);

        jPanel1.setBackground(new java.awt.Color(234, 234, 234));
        jPanel1.setLayout(null);

        regisShopBG.setBackground(new java.awt.Color(153, 255, 153));
        regisShopBG.setLayout(null);

        shopRegisLabelButton.setFont(new java.awt.Font("Cloud Light", 0, 18)); // NOI18N
        shopRegisLabelButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        shopRegisLabelButton.setText("Shop Register");
        shopRegisLabelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        shopRegisLabelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                shopRegisLabelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                shopRegisLabelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                shopRegisLabelButtonMouseExited(evt);
            }
        });
        regisShopBG.add(shopRegisLabelButton);
        shopRegisLabelButton.setBounds(0, 0, 190, 40);

        jPanel1.add(regisShopBG);
        regisShopBG.setBounds(230, 70, 190, 40);

        regisUserBG.setBackground(new java.awt.Color(153, 255, 153));
        regisUserBG.setLayout(null);

        userRegisLabelButton.setFont(new java.awt.Font("Cloud Light", 0, 18)); // NOI18N
        userRegisLabelButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userRegisLabelButton.setText("User Register");
        userRegisLabelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userRegisLabelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userRegisLabelButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userRegisLabelButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                userRegisLabelButtonMouseExited(evt);
            }
        });
        regisUserBG.add(userRegisLabelButton);
        userRegisLabelButton.setBounds(0, 0, 190, 40);

        jPanel1.add(regisUserBG);
        regisUserBG.setBounds(20, 70, 190, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 470, 140);

        setSize(new java.awt.Dimension(464, 173));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void shopRegisLabelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopRegisLabelButtonMouseClicked
        RegisterShop regisShop = new RegisterShop();
        controlLoginEPrinting.setVisible(false);
        this.setVisible(false);
        regisShop.setVisible(true);
    }//GEN-LAST:event_shopRegisLabelButtonMouseClicked

    private void userRegisLabelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userRegisLabelButtonMouseClicked
        RegisterUser regisUser = new RegisterUser();
        controlLoginEPrinting.setVisible(false);
        this.setVisible(false);
        regisUser.setVisible(true);
    }//GEN-LAST:event_userRegisLabelButtonMouseClicked

    private void shopRegisLabelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopRegisLabelButtonMouseEntered
        regisShopBG.setBackground(new java.awt.Color(102, 255, 102));
    }//GEN-LAST:event_shopRegisLabelButtonMouseEntered

    private void shopRegisLabelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shopRegisLabelButtonMouseExited
        regisShopBG.setBackground(new java.awt.Color(153, 255, 153));
    }//GEN-LAST:event_shopRegisLabelButtonMouseExited

    private void userRegisLabelButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userRegisLabelButtonMouseEntered
        regisUserBG.setBackground(new java.awt.Color(102, 255, 102));
    }//GEN-LAST:event_userRegisLabelButtonMouseEntered

    private void userRegisLabelButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userRegisLabelButtonMouseExited
        regisUserBG.setBackground(new java.awt.Color(153, 255, 153));
    }//GEN-LAST:event_userRegisLabelButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectRegisUserOrRegisShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectRegisUserOrRegisShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectRegisUserOrRegisShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectRegisUserOrRegisShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectRegisUserOrRegisShop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel questionSelectRegis;
    private javax.swing.JPanel regisShopBG;
    private javax.swing.JPanel regisUserBG;
    private javax.swing.JLabel shopRegisLabelButton;
    private javax.swing.JLabel userRegisLabelButton;
    // End of variables declaration//GEN-END:variables
}
